name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  key: 
    description: 'Key'
    required: false
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash

    - run: 'echo key: ${{ inputs.key }}'
      if: ${{ inputs.key }}
      shell: bash

    # - name: Checkout repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: waleedahmeddev/ghprb
    #     #ref: master
    #     token: ${{ inputs.key }}
    #     path: ./test/
    
    # - run: ls -la test/
    #   shell: bash

    
