name: 'Composite Test'
description: 'Composite Test'
inputs:
  input_one:
    description: 'input_one'
    required: true
    default: 'empty str'
  key: 
    description: 'key'
    required: false
outputs:
  output_one:
    description: "output_one"
    value: ${{ steps.output_one.outputs.output_var }}
runs:
  using: "composite"
  steps:

    - run: 'echo input_one : ${{ inputs.input_one }}'
      shell: bash

    - id: output_one
      run: echo "output_var=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
      
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash

    - run: 'echo key: ${{ inputs.key }} ${{ runner.name }}'
      if: ${{ inputs.key && contains(runner.name, 'inf-gha-runners-ci') }}
      shell: bash

    - run: 'echo not key: ${{ inputs.key }} ${{ runner.name }}'
      if: ${{ !contains(runner.name, 'inf-gha-runners-ci') || !inputs.key }}
      shell: bash

    # - name: Checkout repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: waleedahmeddev/ghprb
    #     #ref: master
    #     token: ${{ inputs.key }}
    #     path: ./test/
    
    # - run: ls -la test/
    #   shell: bash

    
