name: "My Cache Job"
on: [push]
# fork push

jobs:
  my-cache-job:
    name: Cache Job
    runs-on: ubuntu-latest
    env:
      keyOfCache: test-key-1

    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     repository: waleedtt/cache-action
      #     ref: master
      #     path: ./.github/actions/

      # - uses: ./.github/actions/
      #   with:
      #     sa: ${{ secrets.TEST_JSON_KEY }}
      #     path: |
      #       ./cache
      #     #  ./node_modules
      #     key: ${{ env.keyOfCache }}
      #     # key: ${{ runner.os }}-node-${{ hashFiles('./mywork.txt') }}
      #     # restore-keys: | 
      #     #   test-
      #     # #  test-

      - name: Cache
        id: test-cache
        uses: actions/cache@v3
        #uses: waleedtt/cache-action@master
        with:
          #sa: ${{ secrets.TEST_JSON_KEY }}
          path: |
            ./cache
          #  ./node_modules
          key: ${{ env.keyOfCache }}
          # key: ${{ runner.os }}-node-${{ hashFiles('./mywork.txt') }}
          # restore-keys: | 
          #   test-
          # #  test-

      - name: ls -la
        run: ls -la 

      - name: cat
        run: |
          cat ./cache/mywork.txt || true

      - name: echo 
        run: |
          [ -d cache ] || mkdir cache 
          [ -f cache/mywork.txt ] || echo ${{ env.keyOfCache }} > ./cache/mywork.txt

      - run: 'cd cache && wget https://speed.hetzner.de/100MB.bin'

      - name: ls -la 1
        run: ls -la 

      - name: cat1
        run: cat ./cache/mywork.txt

      # - name: npm install
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      # - name: npm
      #   run: npm install nodemon

      # - name: ls -la 1
      #   run: ls -la 