name: "My Cache Variables"
on: [fork]
# fork push

jobs:
  my-cache-job:
    name: Cache Variables Job
    runs-on: ubuntu-latest
    env:
      keyOfCache: test-key-1

    steps:
      
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      # - name: echo ACTIONS_RUNTIME_TOKEN
      #   run: echo $ACTIONS_RUNTIME_TOKEN | base64 

      # - name: echo ACTIONS_CACHE_URL
      #   run: echo $ACTIONS_CACHE_URL | base64 

      # - name: echo ACTIONS_RUNTIME_URL
      #   run: echo $ACTIONS_RUNTIME_URL | base64 

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      #- run: 'curl -H "Authorization: Bearer $ACTIONS_RUNTIME_TOKEN" -X GET $(echo $ACTIONS_CACHE_URL)_apis/artifactcache/'
