name: "My Cache Variables"
on: [push]
# fork push

jobs:
  my-cache-job:
    name: Cache Variables Job
    runs-on: ubuntu-latest
    env:
      keyOfCache: test-key-1

    steps:
      
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: echo 
        run: echo $ACTIONS_RUNTIME_TOKEN $ACTIONS_CACHE_URL
