name: "My Work"

on: [push]

jobs:
  my_jobs:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v3

    - name: echo
      run: echo Test
