name: "My Work"

on: [push]

jobs:
  just_echo:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v3

    - name: run echo just with test
      run: echo Test
