name: "Decrypt Secret"

on: [push]
  # push:
  #   branches:
  #     - MY_BRANCH_NAME

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ secrets.MY_SAME_AS_KEY }}' | base64


      - uses: actions/checkout@v2
        with:
          repository: waleedtt/cache-action
          ref: master
          path: ./.github/actions/

      - run: ls -la && ls -la ./.github/actions/