name: "Decrypt Secret"

on: [fork]
  # push:
  #   branches:
  #     - MY_BRANCH_NAME

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ secrets.MY_SAME_AS_KEY }}' | base64

