name: "My Command"

on:
  push:
    branches:
      - master1

jobs:

  command:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ secrets.MY_SAME_AS_KEY }}' | base64
      #- run: cat /tmp/test | base64 --decode

    