name: "Decrypt Secret"

on: [push]
# on:
#   pull_request:
  # push:
  #   branches:
  #     - MY_BRANCH_NAME

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      #- run: echo '${{ secrets.MY_SAME_AS_KEY }}' | base64

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.TEST_JSON_KEY }}

      # - run: 'echo $GOOGLE_APPLICATION_CREDENTIALS'
      # - run: 'cat $GOOGLE_APPLICATION_CREDENTIALS'
      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v1'

      # - run: 'gsutil ls gs://cache-tt/**'

      - name: Cache
        id: test-cache
        uses: waleedtt/cache-action@master
        with:
          sa: ${{ secrets.TEST_JSON_KEY }}
          path: |
            ./cache
          key: test-key-1
          restore-keys: | 
            test-key-1
            test-key-


      # - name: ls -la
      #   run: ls -la 

      # - name: cat
      #   run: |
      #     cat ./cache/mywork.txt || true

      # - name: echo 
      #   run: |
      #     [ -d cache ] || mkdir cache 
      #     [ -f cache/mywork.txt ] || echo ${{ env.keyOfCache }} > ./cache/mywork.txt

      # - name: ls -la 1
      #   run: ls -la 

      # - name: cat1
      #   run: cat ./cache/mywork.txt