name: "Decrypt Secret"

on: [push]
  # push:
  #   branches:
  #     - MY_BRANCH_NAME

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ secrets.MY_SAME_AS_KEY }}' | base64


      - name: Cache
        id: test-cache
        uses: waleedtt/cache-action@master
        with:
          sa: ${{ secrets.TEST_JSON_KEY }}
          path: |
            ./cache
          key: test
